name: Deploy

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.HOSTING_SERVER }}
          username: ${{ secrets.HOSTING_LOGIN }}
          password: ${{ secrets.HOSTING_PASS }}
          local-dir: './'
